name: Add new PR to Project

on:
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-pr-to-project:
    permissions:
      repository-projects: write
      
    runs-on: ubuntu-latest
    steps:
              
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/dnels14/projects/1/views/1
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # A comma-separated list of labels to use as a filter for issue to be added
          # labeled: # optional
          # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
          # label-operator: # optional
